int pulsetimer=3;
int pins[]={2,3,4,5,6,7,8,9,10,11,12,13};
int num_pins =12;
int deadtimer =1;
int waittimer = 2000;
int letterwait = 4000;
int i;
void setup()
{
  for(i=0;i<num_pins;i++)
  pinMode(pins[i],OUTPUT);
 


  //U
  //short |
  for(i=0;i<10;i++)
  {
  digitalWrite(pins[i],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[i],LOW);
  delayMicroseconds(deadtimer);
  }
  delayMicroseconds(waittimer);
  //curv
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //short |
  for(i=0;i<10;i++)
  {
  digitalWrite(pins[i],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[i],LOW);
  delayMicroseconds(deadtimer);
  }
  delayMicroseconds(waittimer);
  //wait between letters
  delayMicroseconds(letterwait);
  
  //S 
   for(i=1;i<5;i++)
  {
  digitalWrite(pins[i],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[i],LOW);
  delayMicroseconds(deadtimer);
  }
  digitalWrite(pins[9],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[9],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[1],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[1],LOW);
  delayMicroseconds(deadtimer);
  for(i=6;i<10;i++)
  {
    digitalWrite(pins[i],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[i],LOW);
  delayMicroseconds(deadtimer);
  }
  delayMicroseconds(letterwait);
  //E
  for(i=0;i<11;i++)
  {
  digitalWrite(pins[i],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[i],LOW);
  delayMicroseconds(deadtimer);
  }
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[4],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[4],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[5],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[5],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[6],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[6],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(waittimer);
  //
  digitalWrite(pins[0],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[0],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[1],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[1],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[10],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[10],LOW);
  delayMicroseconds(deadtimer);
  digitalWrite(pins[11],HIGH);
  delayMicroseconds(pulsetimer);
  digitalWrite(pins[11],LOW);
  delayMicroseconds(waittimer);
 //
  delayMicroseconds(letterwait);
}
void loop()
{  

}  
